sites:
  - name: "Vitalik Blog"
    url: "https://vitalik.eth.limo/"
    selector: "li"
    titleSelector: ".post-link"
    linkSelector: ".post-link"
    contentSelector: ".container-fluid.markdown-body.comment-enabled"
    dateSelector: ".post-meta"
outputDir: "public"

