name: Generate RSS Feeds
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours
  workflow_dispatch:

permissions:
  contents: write
  pages: write

jobs:
  generate-feeds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Generate feeds
        run: npm run build

      - name: Deploy to GitHub Pages
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout --orphan gh-pages
          git reset
          cp -r public/* .
          git add .
          git commit -m "Update feeds"
          git push origin gh-pages --force
